<div class="block newsletter">
    <div class="title"><strong>Newsletter </strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?php echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">

            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php echo __('Sign Up for Our Newsletter:') ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?php  echo __('Enter your email address') ?>"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php  echo __('Subscribe sad') ?>" type="submit">
                    <span><?php  echo __('Subscribe') ?></span>
                </button>
            </div>
            <div class="scg-msg">
                <div class="messages">
                </div>
            </div>
        </form>
    </div>
</div>


<script>

    require.config({
        deps: [
            'jquery'
        ],
        callback: function ($) {
            var form = $('form.subscribe');

            form.submit(function(e) {
                if(form.validation('isValid')){
                    var email = $("#newsletter").val();
                    var url = form.attr('action');
                    var loadingMessage = $('#loading-message');

                    if(loadingMessage.length == 0) {
                        form.find('.control').append('<div id="loading-message" style="display:none;padding-top:10px;">&nbsp;</div>');
                        var loadingMessage = $('#loading-message');
                    }

                    e.preventDefault();
                    try{
                        loadingMessage.html('<div style="color:green"><h1>You Are Subscribed</h1></div>').show();
                        $.ajax({
                            url: url,
                            dataType: 'json',
                            type: 'POST',
                            data: {email: email},
                            success: function (data){
                                if(data.status != "ERROR"){
                                    $('#newsletter').val('');
                                }
                                loadingMessage.html(data.msg);
                            },
                            complete: function(){
                                setTimeout(function(){
                                    loadingMessage.hide();
                                },5000);
                            }
                        });
                    } catch (e){
                        loadingMessage.html(e.message);
                    }
                }
                return false;
            });
        }
    })


//    commented
//     require(['jquery'],function($){
//         var form = $('#newsletter-validate-detail');
//         form.submit(function(e) {
//             if(form.validation('isValid')){
//                 var email = $("#newsletter-validate-detail #newsletter").val();
//                 var url = form.attr('action');
//                  var loadingMessage = $('#loading-message');
//
//                 if(loadingMessage.length == 0) {
//                     form.find('.input-group').append('<div id="loading-message" style="display:none;padding-top:10px;color: red;font-size: 13px;">&nbsp;</div>');
//                     var loadingMessage = $('#loading-message');
//                 }
//
//                 e.preventDefault();
//                 try{
//                     loadingMessage.html('Submitting...').show();
//                     $('.scg-msg > messages').html();
//
//                     $.ajax({
//                         url: url,
//                         dataType: 'json',
//                         type: 'POST',
//                         data: {email: email},
//                         success: function (data){
//                             if(data.status != "ERROR"){
//                                 $("#newsletter-validate-detail #newsletter").val('');
//                                 $('#newsletter-validate-detail .scg-msg > .messages').html('<div class="message-success success message" ><div >' +
//                                     data.msg + '</div></div>');
//                             }else{
//                                 $('#newsletter-validate-detail .scg-msg > .messages').html('<div class="message-error error message" >' +
//                                     '<div>'+data.msg +'</div></div>');
//                             }
//                             loadingMessage.html(data.msg);
//                         },
//                     });
//                 } catch (e){
//                     loadingMessage.html(e.message);
//                 }
//             }
//         });
//     })
</script>
